local Config =
{
    [101]=
    {
      id=101,
      name="燃烧伤害",
      des="",
      bufficon="buff_01",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    },
    [102]=
    {
      id=102,
      name="眩晕",
      des="",
      bufficon="",
      buffani="xuanyun",
      buffani_pos=1,
      buffani_scale=1,
      buffani_offset_x=0,
      buffani_offset_y=0.6,
      isfreeze=1,
      isstone=0
    },
    [103]=
    {
      id=103,
      name="持续回血",
      des="",
      bufficon="",
      buffani="chixujiaxue",
      buffani_pos=2,
      buffani_scale=0.6,
      buffani_offset_x=0,
      buffani_offset_y=1,
      isfreeze=0,
      isstone=0
    },
    [104]=
    {
      id=104,
      name="攻击提升",
      des="",
      bufficon="buff_02",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    },
    [105]=
    {
      id=105,
      name="攻击降低",
      des="",
      bufficon="buff_01",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    },
    [106]=
    {
      id=106,
      name="沉默",
      des="",
      bufficon="buff_02",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    },
    [107]=
    {
      id=107,
      name="缴械",
      des="",
      bufficon="buff_01",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    },
    [108]=
    {
      id=108,
      name="伤害加深",
      des="",
      bufficon="buff_01",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    },
    [109]=
    {
      id=109,
      name="标记",
      des="",
      bufficon="buff_02",
      buffani="",
      buffani_pos=0,
      buffani_scale=0,
      buffani_offset_x=0,
      buffani_offset_y=0,
      isfreeze=0,
      isstone=0
    }
}
return Config
