local Config =
{
    [30001]=
    {
      id=30001,
      parts=1,
      baseattribute={2,2},
      attribute_type={0,1},
      attribute_value={1000,5},
      groupid=1,
      exclusiveattr_profession=0,
      exclusiveattr={},
      exclusiveattr_type={},
      exclusiveattr_vaule={}
    },
    [30002]=
    {
      id=30002,
      parts=2,
      baseattribute={1,1},
      attribute_type={0,1},
      attribute_value={10000,5},
      groupid=1,
      exclusiveattr_profession=0,
      exclusiveattr={},
      exclusiveattr_type={},
      exclusiveattr_vaule={}
    },
    [30003]=
    {
      id=30003,
      parts=3,
      baseattribute={2,2},
      attribute_type={0,1},
      attribute_value={1000,5},
      groupid=1,
      exclusiveattr_profession=0,
      exclusiveattr={},
      exclusiveattr_type={},
      exclusiveattr_vaule={}
    },
    [30004]=
    {
      id=30004,
      parts=4,
      baseattribute={1,1},
      attribute_type={0,1},
      attribute_value={10000,5},
      groupid=1,
      exclusiveattr_profession=0,
      exclusiveattr={},
      exclusiveattr_type={},
      exclusiveattr_vaule={}
    },
    [30005]=
    {
      id=30005,
      parts=1,
      baseattribute={2,1},
      attribute_type={0,1},
      attribute_value={888,1},
      groupid=0,
      exclusiveattr_profession=1,
      exclusiveattr={8,9},
      exclusiveattr_type={0,0},
      exclusiveattr_vaule={5,5}
    }
}
return Config
