local Config =
{
    [1]=
    {
      id=1,
      name="阵营光环1",
      des="上阵多个地阵营英雄，激活以下属性",
      icon="campauraicon_001"
    },
    [2]=
    {
      id=2,
      name="阵营光环2",
      des="上阵多个水阵营英雄，激活以下属性",
      icon="campauraicon_002"
    },
    [3]=
    {
      id=3,
      name="阵营光环3",
      des="上阵多个火阵营英雄，激活以下属性",
      icon="campauraicon_003"
    },
    [4]=
    {
      id=4,
      name="阵营光环4",
      des="上阵多个封阵营英雄，激活以下属性",
      icon="campauraicon_004"
    },
    [5]=
    {
      id=5,
      name="阵营光环5",
      des="上阵多个光阵营英雄，激活以下属性",
      icon="campauraicon_001"
    },
    [6]=
    {
      id=6,
      name="阵营光环6",
      des="上阵多个暗阵营英雄，激活以下属性",
      icon="campauraicon_002"
    },
    [7]=
    {
      id=7,
      name="阵营光环7",
      des="上阵多个超阵营英雄，激活以下属性",
      icon="campauraicon_003"
    },
    [8]=
    {
      id=8,
      name="混色光环",
      des="上阵六个不同阵营英雄，激活以下属性",
      icon="campauraicon_004"
    }
}
return Config
