local Config =
{
    [1]=
    {
      tier=0,
      name="0",
      coin=10000,
      upgrade_item=20007,
      upgrade_num=50,
      hero_list={},
      hero_num={},
      hero_quality={}
    },
    [2]=
    {
      tier=1,
      name="I",
      coin=50000,
      upgrade_item=20007,
      upgrade_num=200,
      hero_list={},
      hero_num={},
      hero_quality={}
    },
    [3]=
    {
      tier=2,
      name="II",
      coin=100000,
      upgrade_item=20007,
      upgrade_num=400,
      hero_list={},
      hero_num={},
      hero_quality={}
    },
    [4]=
    {
      tier=3,
      name="III",
      coin=500000,
      upgrade_item=20007,
      upgrade_num=1000,
      hero_list={},
      hero_num={},
      hero_quality={}
    },
    [5]=
    {
      tier=4,
      name="IV",
      coin=1000000,
      upgrade_item=20007,
      upgrade_num=2000,
      hero_list={},
      hero_num={},
      hero_quality={}
    },
    [6]=
    {
      tier=5,
      name="V",
      coin=5000000,
      upgrade_item=20007,
      upgrade_num=2000,
      hero_list={2},
      hero_num={4},
      hero_quality={5}
    },
    [7]=
    {
      tier=6,
      name="VI",
      coin=10000000,
      upgrade_item=20007,
      upgrade_num=3000,
      hero_list={2,2},
      hero_num={3,1},
      hero_quality={5,6}
    },
    [8]=
    {
      tier=7,
      name="VII",
      coin=50000000,
      upgrade_item=20007,
      upgrade_num=4000,
      hero_list={1,2,2},
      hero_num={1,2,2},
      hero_quality={5,5,6}
    },
    [9]=
    {
      tier=8,
      name="VIII",
      coin=0,
      upgrade_item=0,
      upgrade_num=0,
      hero_list={},
      hero_num={},
      hero_quality={}
    }
}
return Config
