local Config =
{
    ["ANDROID_RETURN"]=
    {
      type=1,
      str="是否确认离开游戏？"
    },
    ["MAX_TEXT"]=
    {
      type=1,
      str="MAX"
    },
    ["HERO_LV_TEXT_FORMAT"]=
    {
      type=1,
      str="%s/%s"
    },
    ["HERO_BUY_CELL_ALERT"]=
    {
      type=1,
      str="是否花费%s钻石购买5个携带上限？"
    },
    ["CONSUME_NUM_FORMAT_ENOUGH"]=
    {
      type=1,
      str="<color=#ffffff>%s/%s</color>"
    },
    ["CONSUME_NUM_FORMAT_NOT_ENOUGH"]=
    {
      type=1,
      str="<color=#ff0000>%s/%s</color>"
    },
    ["CONSUME_NUM_FORMAT_ENOUGH_1"]=
    {
      type=1,
      str="<color=#ffffff>%s</color>"
    },
    ["CONSUME_NUM_FORMAT_NOT_ENOUGH_1"]=
    {
      type=1,
      str="<color=#ff0000>%s</color>"
    },
    ["ITEM_NAME_FORMAT"]=
    {
      type=1,
      str="<color=%s>%s</color>"
    },
    ["ITEM_COUNT_NOT_ENOUGH"]=
    {
      type=1,
      str="道具数量不足"
    },
    ["EQUIP_ATTRIBUTE_DESC_1"]=
    {
      type=1,
      str="<color=#ffffff>+%s \r\t%s</color>"
    },
    ["EQUIP_ATTRIBUTE_DESC_2"]=
    {
      type=1,
      str="<color=#707070>+%s \r\t%s</color>"
    },
    ["EQUIP_ATTRIBUTE_DESC_3"]=
    {
      type=1,
      str="<color=#F3AA05>%s装备套装(%s/4)</color>"
    },
    ["EQUIP_ATTRIBUTE_DESC_4"]=
    {
      type=1,
      str="<color=#F3AA05>专属效果激活：%s</color>"
    },
    ["SHOP_REFRESH_WARNNING_TIP"]=
    {
      type=1,
      str="刷新需要花费%s%s，是否继续"
    },
    ["SHOP_BUY_ITEM_ALERT"]=
    {
      type=1,
      str="是否确认购买？"
    },
    ["HANG_UP_CURR_PVE_NAME"]=
    {
      type=1,
      str="STAGE %s"
    },
    ["HANG_UP_PVE_CONDITION_ENOUGH"]=
    {
      type=1,
      str="<color=#ffffff>%s</color>"
    },
    ["HANG_UP_PVE_CONDITION_NOT_ENOUGH"]=
    {
      type=1,
      str="<color=#ff0000>%s</color>"
    },
    ["HANG_UP_INCOME_FORMAT"]=
    {
      type=1,
      str="+%s/5s"
    },
    ["REWARD_QUICK_TIP"]=
    {
      type=1,
      str="确认消耗%s钻石立即完成该任务？"
    }
}
return Config
