//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CFramework_LuaComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CFramework.LuaComponent), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("New", New);
		L.RegFunction("UpdateControlBind", UpdateControlBind);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int New(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			CFramework.LuaComponent obj = (CFramework.LuaComponent)ToLua.CheckObject<CFramework.LuaComponent>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			CFramework.BaseView arg1 = (CFramework.BaseView)ToLua.CheckObject<CFramework.BaseView>(L, 3);
			obj.New(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateControlBind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CFramework.LuaComponent obj = (CFramework.LuaComponent)ToLua.CheckObject<CFramework.LuaComponent>(L, 1);
			obj.UpdateControlBind();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

