//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CFramework_FileUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CFramework.FileUtil), typeof(CFramework.Singleton<CFramework.FileUtil>));
		L.RegFunction("GetAssetsPath", GetAssetsPath);
		L.RegFunction("GetResPath", GetResPath);
		L.RegFunction("GetWritePath", GetWritePath);
		L.RegFunction("CopyFolderTo", CopyFolderTo);
		L.RegFunction("New", _CreateCFramework_FileUtil);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCFramework_FileUtil(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CFramework.FileUtil obj = new CFramework.FileUtil();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CFramework.FileUtil.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAssetsPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CFramework.FileUtil obj = (CFramework.FileUtil)ToLua.CheckObject<CFramework.FileUtil>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetAssetsPath(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CFramework.FileUtil obj = (CFramework.FileUtil)ToLua.CheckObject<CFramework.FileUtil>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetResPath(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWritePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CFramework.FileUtil obj = (CFramework.FileUtil)ToLua.CheckObject<CFramework.FileUtil>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetWritePath(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyFolderTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			CFramework.FileUtil obj = (CFramework.FileUtil)ToLua.CheckObject<CFramework.FileUtil>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.CopyFolderTo(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

