local Message = {}

--战斗
Message.BATTLE = 5000
Message.BATTLE_TYPE_START = "BATTLE_TYPE_START"
Message.BATTLE_TYPE_ATTACK = "BATTLE_TYPE_ATTACK"
Message.BATTLE_TYPE_CASTSKILL = "BATTLE_TYPE_CASTSKILL"
Message.BATTLE_TYPE_DAMAGE = "BATTLE_TYPE_DAMAGE"
Message.BATTLE_TYPE_RECOVER = "BATTLE_TYPE_RECOVER"
Message.BATTLE_TYPE_PARRYING = "BATTLE_TYPE_PARRYING"
Message.BATTLE_TYPE_COUNTERATTACK = "BATTLE_TYPE_COUNTERATTACK"
Message.BATTLE_TYPE_IMPRISON = "BATTLE_TYPE_IMPRISON"
Message.BATTLE_TYPE_HERO_ACTION_COMPLETE = "BATTLE_TYPE_HERO_ACTION_COMPLETE"
Message.BATTLE_TYPE_NEXT_ROUND = "BATTLE_TYPE_NEXT_ROUND"
Message.BATTLE_TYPE_BUFF_ADD = "BATTLE_TYPE_BUFF_ADD"
Message.BATTLE_TYPE_BUFF_CD = "BATTLE_TYPE_BUFF_CD"
Message.BATTLE_TYPE_RAGE_UPDATE = "BATTLE_TYPE_RAGE_UPDATE"
Message.BATTLE_TYPE_REVIVE = "BATTLE_TYPE_REVIVE"
Message.BATTLE_TYPE_MISS = "BATTLE_TYPE_MISS"


return Message